[package]
name = "mesita"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.36", features = ["derive"] }
crossterm = { version = "0.29.0", features = ["use-dev-tty"] }
csv = "1.3.1"
ratatui = "0.29.0"
